/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package lumberdb;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Mathew.schulz
 */
public class LumberDBSwing extends javax.swing.JFrame {

    /**
     * Creates new form LumberDBSwing
     */
    public LumberDBSwing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WSQLE_Title = new javax.swing.JLabel();
        q_L = new javax.swing.JLabel();
        q_CB = new javax.swing.JComboBox();
        sqButton = new javax.swing.JButton();
        sq_LV = new javax.swing.JLabel();
        sq_L = new javax.swing.JLabel();
        QueryContainer = new javax.swing.JLayeredPane();
        CreateTransactionPanel = new javax.swing.JPanel();
        bNo_LCT = new javax.swing.JLabel();
        cName_LCT = new javax.swing.JLabel();
        cName_TFCT = new javax.swing.JTextField();
        bNo_TFCT = new javax.swing.JTextField();
        sButtonCT = new javax.swing.JButton();
        MillBundlePanel = new javax.swing.JLayeredPane();
        mType_LMB = new javax.swing.JLabel();
        bNo_LMB = new javax.swing.JLabel();
        notes_LMB = new javax.swing.JLabel();
        bNo_TFMB = new javax.swing.JTextField();
        notes_TFMB = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        sButtonMB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        WSQLE_Title.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        WSQLE_Title.setText("Worst SQL Ever Lumber Yard DB");

        q_L.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        q_L.setText("Query:");

        q_CB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        q_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mill Bundle", "Ship Bundle", "Create Bundle", "Create Salesmen", "Create Client", "Create Warehouse-Mill", "Create Transaction", "Count Warehouse Stock", "Update Transaction", "Break Bundle", "Count All Bundles", "Update Bundle Price", "Move Bundle" }));
        q_CB.setToolTipText("Select the Query you want to run");

        sqButton.setText("Select Query");

        sq_LV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sq_LV.setText("N/A");
        sq_LV.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                sq_LVComponentShown(evt);
            }
        });
        sq_LV.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sq_LVPropertyChange(evt);
            }
        });

        sq_L.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        sq_L.setText("Selected Query:");

        CreateTransactionPanel.setEnabled(false);
        CreateTransactionPanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CreateTransactionPanelAppearOn(evt);
            }
        });

        bNo_LCT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bNo_LCT.setText("Bundle Number:");
        bNo_LCT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bNo_LCTAppearOn(evt);
            }
        });

        cName_LCT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cName_LCT.setText("Company Name:");

        cName_TFCT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cName_TFCT.setToolTipText("Enter the Company Name");
        cName_TFCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cName_TFCTActionPerformed(evt);
            }
        });

        bNo_TFCT.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bNo_TFCT.setToolTipText("Enter the Bundle Number");
        bNo_TFCT.setFocusable(false);

        sButtonCT.setText("Submit");

        javax.swing.GroupLayout CreateTransactionPanelLayout = new javax.swing.GroupLayout(CreateTransactionPanel);
        CreateTransactionPanel.setLayout(CreateTransactionPanelLayout);
        CreateTransactionPanelLayout.setHorizontalGroup(
            CreateTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateTransactionPanelLayout.createSequentialGroup()
                .addGroup(CreateTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateTransactionPanelLayout.createSequentialGroup()
                        .addComponent(bNo_LCT, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(cName_TFCT, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(CreateTransactionPanelLayout.createSequentialGroup()
                        .addComponent(cName_LCT, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(CreateTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bNo_TFCT)
                            .addComponent(sButtonCT, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        CreateTransactionPanelLayout.setVerticalGroup(
            CreateTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateTransactionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CreateTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNo_LCT, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(cName_TFCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CreateTransactionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cName_LCT)
                    .addComponent(bNo_TFCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sButtonCT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MillBundlePanel.setEnabled(false);
        MillBundlePanel.setPreferredSize(new java.awt.Dimension(661, 156));
        MillBundlePanel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                MillBundlePanelAppearOn(evt);
                MillBundlePanelAppearOnMB(evt);
            }
        });

        mType_LMB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        mType_LMB.setText("Milled Type:");
        mType_LMB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mType_LMBAppearOn(evt);
            }
        });

        bNo_LMB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bNo_LMB.setText("Bundle Number:");
        bNo_LMB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                bNo_LMBAppearOn(evt);
            }
        });

        notes_LMB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        notes_LMB.setText("Notes:");
        notes_LMB.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                notes_LMBAppearOn(evt);
            }
        });

        bNo_TFMB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        bNo_TFMB.setToolTipText("Enter the Bundle Number");
        bNo_TFMB.setFocusable(false);

        notes_TFMB.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        notes_TFMB.setToolTipText("Enter the Bundle Number");
        notes_TFMB.setFocusable(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        sButtonMB.setText("Submit");

        javax.swing.GroupLayout MillBundlePanelLayout = new javax.swing.GroupLayout(MillBundlePanel);
        MillBundlePanel.setLayout(MillBundlePanelLayout);
        MillBundlePanelLayout.setHorizontalGroup(
            MillBundlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MillBundlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MillBundlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MillBundlePanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(mType_LMB))
                    .addComponent(bNo_LMB)
                    .addComponent(notes_LMB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(30, 30, 30)
                .addGroup(MillBundlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bNo_TFMB)
                    .addGroup(MillBundlePanelLayout.createSequentialGroup()
                        .addComponent(sButtonMB, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(notes_TFMB))
                .addContainerGap())
        );
        MillBundlePanelLayout.setVerticalGroup(
            MillBundlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MillBundlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MillBundlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MillBundlePanelLayout.createSequentialGroup()
                        .addGroup(MillBundlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bNo_LMB)
                            .addComponent(bNo_TFMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(mType_LMB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(MillBundlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notes_TFMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notes_LMB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sButtonMB, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        MillBundlePanel.setLayer(mType_LMB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MillBundlePanel.setLayer(bNo_LMB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MillBundlePanel.setLayer(notes_LMB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MillBundlePanel.setLayer(bNo_TFMB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MillBundlePanel.setLayer(notes_TFMB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MillBundlePanel.setLayer(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        MillBundlePanel.setLayer(sButtonMB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout QueryContainerLayout = new javax.swing.GroupLayout(QueryContainer);
        QueryContainer.setLayout(QueryContainerLayout);
        QueryContainerLayout.setHorizontalGroup(
            QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueryContainerLayout.createSequentialGroup()
                .addGroup(QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MillBundlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateTransactionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 302, Short.MAX_VALUE))
        );
        QueryContainerLayout.setVerticalGroup(
            QueryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(QueryContainerLayout.createSequentialGroup()
                .addComponent(CreateTransactionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MillBundlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        QueryContainer.setLayer(CreateTransactionPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        QueryContainer.setLayer(MillBundlePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(WSQLE_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sq_L)
                                    .addComponent(q_L))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(q_CB, 0, 380, Short.MAX_VALUE)
                                    .addComponent(sq_LV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sqButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(QueryContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(WSQLE_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q_CB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q_L, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sqButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sq_L, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sq_LV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(QueryContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sq_LVComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_sq_LVComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_sq_LVComponentShown

    private void sq_LVPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sq_LVPropertyChange
        // TODO add your handling code here:
        sqButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                sq_LV.setText(q_CB.getSelectedItem().toString());

            }
        });
    }//GEN-LAST:event_sq_LVPropertyChange

    private void bNo_LCTAppearOn(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bNo_LCTAppearOn
        // TODO add your handling code here:
        CreateTransactionPanel.setVisible(false);
        sqButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {

                if (q_CB.getSelectedItem() == "Create Transaction") {
                    CreateTransactionPanel.setEnabled(true);
                    CreateTransactionPanel.setVisible(true);
                } else {
                    CreateTransactionPanel.setEnabled(false);
                    CreateTransactionPanel.setVisible(false);
                }
            }
        });
    }//GEN-LAST:event_bNo_LCTAppearOn

    private void cName_TFCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cName_TFCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cName_TFCTActionPerformed

    private void CreateTransactionPanelAppearOn(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CreateTransactionPanelAppearOn
        // TODO add your handling code here:
        CreateTransactionPanel.setVisible(false);
        sqButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {

                if (q_CB.getSelectedItem() == "Create Transaction") {
                    CreateTransactionPanel.setEnabled(true);
                    CreateTransactionPanel.setVisible(true);
                } else {
                    CreateTransactionPanel.setEnabled(false);
                    CreateTransactionPanel.setVisible(false);
                }
            }
        });
    }//GEN-LAST:event_CreateTransactionPanelAppearOn

    private void mType_LMBAppearOn(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mType_LMBAppearOn
        // TODO add your handling code here:
    }//GEN-LAST:event_mType_LMBAppearOn

    private void bNo_LMBAppearOn(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_bNo_LMBAppearOn
        // TODO add your handling code here:
    }//GEN-LAST:event_bNo_LMBAppearOn

    private void notes_LMBAppearOn(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_notes_LMBAppearOn
        // TODO add your handling code here:
    }//GEN-LAST:event_notes_LMBAppearOn

    private void MillBundlePanelAppearOn(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MillBundlePanelAppearOn
        // TODO add your handling code here:
        MillBundlePanel.setVisible(false);
        sqButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent arg0) {

                if (q_CB.getSelectedItem() == "Mill Bundle") {
                    MillBundlePanel.setEnabled(true);
                    MillBundlePanel.setVisible(true);
                } else {
                    MillBundlePanel.setEnabled(false);
                    MillBundlePanel.setVisible(false);
                }
            }
        });
    }//GEN-LAST:event_MillBundlePanelAppearOn

    private void MillBundlePanelAppearOnMB(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_MillBundlePanelAppearOnMB
        // TODO add your handling code here:

    }//GEN-LAST:event_MillBundlePanelAppearOnMB

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LumberDBSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LumberDBSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LumberDBSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LumberDBSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LumberDBSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreateTransactionPanel;
    private javax.swing.JLayeredPane MillBundlePanel;
    private javax.swing.JLayeredPane QueryContainer;
    private javax.swing.JLabel WSQLE_Title;
    private javax.swing.JLabel bNo_LCT;
    private javax.swing.JLabel bNo_LMB;
    private javax.swing.JTextField bNo_TFCT;
    private javax.swing.JTextField bNo_TFMB;
    private javax.swing.JLabel cName_LCT;
    private javax.swing.JTextField cName_TFCT;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel mType_LMB;
    private javax.swing.JLabel notes_LMB;
    private javax.swing.JTextField notes_TFMB;
    private javax.swing.JComboBox q_CB;
    private javax.swing.JLabel q_L;
    private javax.swing.JButton sButtonCT;
    private javax.swing.JButton sButtonMB;
    private javax.swing.JButton sqButton;
    private javax.swing.JLabel sq_L;
    private javax.swing.JLabel sq_LV;
    // End of variables declaration//GEN-END:variables
}
